import React from 'react';

import { NextPage } from 'next';

import Head from 'next/head';

import { Layout } from 'environment/Layout';
import { PlatformPage } from 'sections/PlatformPage';

const Platform: NextPage = () => {
  return (
    <>
      <Head>
        <title>Платформа</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PlatformPage />
      </Layout>
    </>
  );
};

export default Platform;
