import React from 'react';

import { NextPage } from 'next';

import Head from 'next/head';

import { AuthorizationPage } from 'sections/AuthorizationPage';

const Authorization: NextPage = () => {
  return (
    <>
      <Head>
        <title>smart dialogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthorizationPage />
    </>
  );
};

export default Authorization;
