import React from 'react';

import Head from 'next/head';

import { Layout } from 'environment/Layout/Layout';
import { MainPageContent } from 'sections/MainPageContent';

export default function Home() {
  return (
    <>
      <Head>
        <title>smart dialogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <MainPageContent />
      </Layout>
    </>
  );
}
